FROM ubuntu
ENV PATH="/:${PATH}"

# Install vnc, xvfb in order to create a 'fake' display and firefox
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 \
    python3-pip \
    python-is-python3 \
    curl \
    make

WORKDIR /django_project

COPY ["/django_project/", "/django_project/"]

RUN python3 -m pip install -r requirements.txt

COPY ["entrypoint.sh", "/"]

EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080 || exit 1

VOLUME ["/django_project/config", "/django_project/log"]

ENTRYPOINT [ "bash", "/entrypoint.sh" ]