# Generated by Django 3.1.7 on 2021-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='event',
        ),
        migrations.AddField(
            model_name='location',
            name='attendees',
            field=models.ManyToManyField(to='sse_finder.Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
