# Generated by Django 3.2 on 2021-04-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='Event',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Description_of_event',
            new_name='description_of_event',
        ),
    ]
