# Generated by Django 3.1.7 on 2021-04-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0002_auto_20210424_0935'),
        ('sse_finder', '0002_auto_20210424_0925'),
    ]

    operations = [
    ]
