# Generated by Django 3.2 on 2021-04-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0003_merge_20210425_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
