# Generated by Django 3.1.7 on 2021-04-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0004_auto_20210426_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinate_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='coordinate_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
