# Generated by Django 3.1.7 on 2021-04-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0005_auto_20210427_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='venue_name',
        ),
    ]
