# Generated by Django 3.2 on 2021-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0005_chp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_possible_infected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_possible_infector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chp_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
