# Generated by Django 3.2 on 2021-05-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0006_auto_20210505_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_possible_infected',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_possible_infector',
        ),
    ]
