# Generated by Django 3.1.7 on 2021-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0006_auto_20210427_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='case_num',
            field=models.IntegerField(null=True),
        ),
    ]
