# Generated by Django 3.1.7 on 2021-04-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sse_finder', '0007_location_case_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='case_num',
        ),
    ]
